### ISSUE TITLE
HM_spezifisch -> generisch....

### ISSUE THREAD

**Issue by apunkt** [domcross/fhem-skill#5]
https://github.com/domcross/fhem-skill/blob/c7d06c199d8deef92c4e28036a2f1a8d2dbdb811/__init__.py#L485

Anstelle des Devices kann man doch bei HM Geräten einfach den Clima-Kanal verwenden, sprich direkt auswählen. Ich setze dafür ein Alias in fhem. Dann braucht man _Clima nicht automatisch setzen und dann würde es auch mit FHT80b funktionieren...

**Comment by domcross** [comment]
Mit dem letzten [Commit](https://github.com/domcross/fhem-skill/commit/9d2e4a27fb7bf05e1da9535fdf4d4f7d6e52f1a6) ist eine Erkennung verschiedener Thermostat Typen vorhanden (von [homebridge-fhem](https://github.com/justme-1968/homebridge-fhem/blob/master/index.js) übernommen). 
Für Devices vom Typ CUL_HM wird geprüft ob das Device einen channel_04 hat (Clima) und entsprechend damit umgegangen - man kann auch den Clima-Kanal direkt verwenden.
(Mangels FHT80b kann ich aber nicht prüfen, ob das auch damit funktioniert...)

**Comment by apunkt** [comment]
Leider funktioniert das bei mir nicht:
Bei HM (ich verwende den Channel 4 selbst als Entity) als auch FHT80b:
11:49:33.413 - mycroft.skills.core:wrapper:745 - ERROR - An error occurred while processing a request in Fhem Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 736, in wrapper
    handler(message)
  File "/opt/mycroft/skills/fhem-skill.domcross/__init__.py", line 495, in handle_set_thermostat_intent
    if 'desired-temp' in td['Readings']:
TypeError: 'NoneType' object is not subscriptable
~~~~t": {}, "data": {"name": "FhemSkill.handle_set_thermostat_intent", "exception": "TypeError(\"'NoneType' object is not subscriptable\",)"}}

zudem habe ich mal für FHT was eingefügt

**Comment by apunkt** [comment]
Der Type Error kommt bei mir vor, weil meine Thermostate über den korrekten Namen angesprochen werden, ich für mycroft aber in fhem einen gut klingenden alias angelegt habe.
Rufe ich via Mycroft den leicht zu sprechenden Alias auf, klappt das nicht, weil er nach dem nicht vorhandenen Device-Namen sucht.
Interessanterweise funktioniert alias aber mit allen anderen genericDeviceTypes ...
Ich hatte diesen Weg gewählt, weil ich meine Device-Namen nach einer logischen aber schlecht zu sprechenden Struktur aufgebaut habe und diese in zahlreichen Notifies etc. verbaut sind.

**Comment by domcross** [comment]
Fehler bei Verwendung Alias ist gefixt

**Comment by apunkt** [comment]
Perfekt.
Läuft (auch mit FHT)!
